package com.happy.hack.hibernate.entity;

// Generated 12 Apr, 2015 12:33:13 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BiGram generated by hbm2java
 */
@Entity
@Table(name = "BiGram", catalog = "Happyhack")
public class BiGram implements java.io.Serializable {

	private Integer idRawTable;
	private String content;
	private float overall;
	private float value;
	private float rooms;
	private float locations;
	private float cleanliness;
	private float chekIn;
	private float service;
	private float businessService;
	private int sleepQuality;

	public BiGram() {
	}

	public BiGram(float overall, float value, float rooms, float locations,
			float cleanliness, float chekIn, float service,
			float businessService, int sleepQuality) {
		this.overall = overall;
		this.value = value;
		this.rooms = rooms;
		this.locations = locations;
		this.cleanliness = cleanliness;
		this.chekIn = chekIn;
		this.service = service;
		this.businessService = businessService;
		this.sleepQuality = sleepQuality;
	}

	public BiGram(String content, float overall, float value, float rooms,
			float locations, float cleanliness, float chekIn, float service,
			float businessService, int sleepQuality) {
		this.content = content;
		this.overall = overall;
		this.value = value;
		this.rooms = rooms;
		this.locations = locations;
		this.cleanliness = cleanliness;
		this.chekIn = chekIn;
		this.service = service;
		this.businessService = businessService;
		this.sleepQuality = sleepQuality;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRawTable", unique = true, nullable = false)
	public Integer getIdRawTable() {
		return this.idRawTable;
	}

	public void setIdRawTable(Integer idRawTable) {
		this.idRawTable = idRawTable;
	}

	@Column(name = "Content", length = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "Overall", nullable = false, precision = 12, scale = 0)
	public float getOverall() {
		return this.overall;
	}

	public void setOverall(float overall) {
		this.overall = overall;
	}

	@Column(name = "Value", nullable = false, precision = 12, scale = 0)
	public float getValue() {
		return this.value;
	}

	public void setValue(float value) {
		this.value = value;
	}

	@Column(name = "Rooms", nullable = false, precision = 12, scale = 0)
	public float getRooms() {
		return this.rooms;
	}

	public void setRooms(float rooms) {
		this.rooms = rooms;
	}

	@Column(name = "Locations", nullable = false, precision = 12, scale = 0)
	public float getLocations() {
		return this.locations;
	}

	public void setLocations(float locations) {
		this.locations = locations;
	}

	@Column(name = "Cleanliness", nullable = false, precision = 12, scale = 0)
	public float getCleanliness() {
		return this.cleanliness;
	}

	public void setCleanliness(float cleanliness) {
		this.cleanliness = cleanliness;
	}

	@Column(name = "ChekIn", nullable = false, precision = 12, scale = 0)
	public float getChekIn() {
		return this.chekIn;
	}

	public void setChekIn(float chekIn) {
		this.chekIn = chekIn;
	}

	@Column(name = "Service", nullable = false, precision = 12, scale = 0)
	public float getService() {
		return this.service;
	}

	public void setService(float service) {
		this.service = service;
	}

	@Column(name = "BusinessService", nullable = false, precision = 12, scale = 0)
	public float getBusinessService() {
		return this.businessService;
	}

	public void setBusinessService(float businessService) {
		this.businessService = businessService;
	}

	@Column(name = "SleepQuality", nullable = false)
	public int getSleepQuality() {
		return this.sleepQuality;
	}

	public void setSleepQuality(int sleepQuality) {
		this.sleepQuality = sleepQuality;
	}

}
